# Generated by Django 3.1.6 on 2021-02-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('email_id', models.EmailField(max_length=120)),
                ('phonenumber', models.IntegerField(unique=True)),
            ],
        ),
    ]
