# Generated by Django 3.1.6 on 2021-02-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfomodel',
            name='ifs_code',
            field=models.CharField(max_length=12),
        ),
    ]
