# Generated by Django 3.1.6 on 2021-02-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_transfermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfermodel',
            old_name='username',
            new_name='user',
        ),
    ]
