# Generated by Django 3.1.6 on 2021-02-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_remove_transfermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermodel',
            name='accno',
            field=models.CharField(max_length=6),
        ),
    ]
